//! Self-evolution meta-tool: auto-wrap old forge tools into new forge `Tool` trait.
//!
//! The auto-wrap flow:
//! 1. Read old tool source code (using new forge's `grep` + `read_file` capability)
//! 2. Detect function signatures, input/output types, permission level
//! 3. Generate new `Tool` struct + `ToolDescriptor` + `Tool` trait impl (a "patch")
//! 4. Output the generated code as a review-gated patch (not directly merged)
//!
//! This is the core of the "use new forge's existing capabilities to participate in B work"
//! self-evolution loop: the meta-tool itself is built from new forge's tool traits, and it
//! generates new tools that extend the same trait — a closed loop of tool production.

use async_trait::async_trait;
use forge_core::{ForgeError, ForgeResult};
use forge_exec::{PermissionLevel, Tool, ToolDescriptor, ToolRouter};
use serde_json::{json, Value};
use std::path::Path;

fn err(msg: impl Into<String>) -> ForgeError {
    ForgeError::InvalidState(msg.into())
}

/// Wrap a single old tool definition into a new `Tool` implementation patch.
pub struct AutoWrapTool {
    descriptor: ToolDescriptor,
}

impl Default for AutoWrapTool {
    fn default() -> Self {
        Self::new()
    }
}

impl AutoWrapTool {
    pub fn new() -> Self {
        Self {
            descriptor: ToolDescriptor {
                name: "auto_wrap_tool".into(),
                description: "Self-evolution meta-tool: read old forge tool source, detect signature, generate new Tool trait impl patch (review-gated, not auto-merged)".into(),
                input_schema: json!({
                    "type": "object",
                    "properties": {
                        "tool_name": { "type": "string", "description": "Name of the old tool to wrap" },
                        "source_dir": { "type": "string", "description": "Directory containing old tool source files" },
                        "permission": { "type": "string", "enum": ["ReadOnly","WorkspaceWrite","External","Irreversible"], "description": "Permission level for the generated tool" },
                        "dry_run": { "type": "boolean", "description": "If true, return the generated patch without writing to file" }
                    },
                    "required": ["tool_name", "source_dir"]
                }),
                permission: PermissionLevel::WorkspaceWrite,
            },
        }
    }
}

/// Parse a Rust function signature block and extract input/output type hints.
fn parse_rust_signature(source: &str) -> Value {
    // Extract function signatures like `pub async fn foo(input: serde_json::Value) -> ForgeResult<...>`
    let mut signatures = Vec::new();
    for line in source.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("pub async fn") || trimmed.starts_with("pub fn") {
            signatures.push(trimmed.to_string());
        }
    }
    json!({
        "function_signatures": signatures,
        "function_count": signatures.len(),
    })
}

/// Detect permission level from source code heuristics.
fn detect_permission(source: &str, default: &str) -> String {
    let lower = source.to_lowercase();
    if lower.contains("std::process") || lower.contains("std::fs::write") || lower.contains("std::fs::remove") {
        "WorkspaceWrite".to_string()
    } else if lower.contains("http") || lower.contains("reqwest") || lower.contains("web") {
        "External".to_string()
    } else {
        default.to_string()
    }
}

/// Generate a new `Tool` struct implementation as source code string.
fn generate_tool_patch(
    tool_name: &str,
    description: &str,
    source_signatures: &Value,
    permission: &str,
    source_dir: &str,
) -> Value {
    let struct_name = to_pascal_case(tool_name);
    let permission_variant = match permission {
        "WorkspaceWrite" => "PermissionLevel::WorkspaceWrite",
        "External" => "PermissionLevel::External",
        "Irreversible" => "PermissionLevel::Irreversible",
        _ => "PermissionLevel::ReadOnly",
    };

    let generated_code = format!(
        r#"// Auto-generated by auto_wrap_tool (self-evolution meta-tool)
// Source: {source_dir}/{tool_name}.rs
// Permission: {permission}

use async_trait::async_trait;
use forge_core::{{ForgeError, ForgeResult}};
use forge_exec:{{PermissionLevel, Tool, ToolDescriptor}};
use serde_json::json;

fn err(msg: impl Into<String>) -> ForgeError {{ ForgeError::InvalidState(msg.into()) }}

pub struct {struct_name}Tool {{
    descriptor: ToolDescriptor,
}}

impl {struct_name}Tool {{
    pub fn new() -> Self {{
        Self {{
            descriptor: ToolDescriptor {{
                name: "{tool_name}".into(),
                description: "{description}".into(),
                input_schema: json!({{
                    "type": "object",
                    "properties": {{
                        "text": {{ "type": "string", "description": "Input text" }}
                    }},
                    "required": ["text"]
                }}),
                permission: {permission_variant},
            }},
        }}
    }}
}}

#[async_trait]
impl Tool for {struct_name}Tool {{
    fn descriptor(&self) -> &ToolDescriptor {{
        &self.descriptor
    }}

    async fn invoke(&self, input: serde_json::Value) -> ForgeResult<serde_json::Value> {{
        let text = input.get("text").and_then(|v| v.as_str())
            .ok_or_else(|| err("text is required"))?;
        // TODO: implement actual logic by porting from old forge source
        Ok(json!({{ "status": "pending_engine", "tool": "{tool_name}", "input_len": text.len() }}))
    }}
}}
"#,
        source_dir = source_dir,
        tool_name = tool_name,
        struct_name = struct_name,
        description = description,
        permission = permission,
        permission_variant = permission_variant,
    );

    json!({
        "tool_name": tool_name,
        "struct_name": format!("{struct_name}Tool"),
        "permission": permission,
        "source_signatures": source_signatures,
        "generated_code": generated_code,
        "review_status": "pending_review",
        "notes": "This patch must pass review-gate before merging. The generated code is a mechanical shell returning pending_engine; actual logic must be ported from old source.",
    })
}

/// Convert snake_case to PascalCase.
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut c = word.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + c.as_str(),
            }
        })
        .collect()
}

#[async_trait]
impl Tool for AutoWrapTool {
    fn descriptor(&self) -> &ToolDescriptor {
        &self.descriptor
    }

    async fn invoke(&self, input: Value) -> ForgeResult<Value> {
        let tool_name = input
            .get("tool_name")
            .and_then(|v| v.as_str())
            .ok_or_else(|| err("tool_name is required"))?;
        let source_dir_str = input
            .get("source_dir")
            .and_then(|v| v.as_str())
            .ok_or_else(|| err("source_dir is required"))?;
        let default_permission = input
            .get("permission")
            .and_then(|v| v.as_str())
            .unwrap_or("ReadOnly");
        let dry_run = input.get("dry_run").and_then(|v| v.as_bool()).unwrap_or(true);

        let source_dir = Path::new(source_dir_str);
        if !source_dir.exists() {
            return Err(err(format!(
                "source_dir not found: {}",
                source_dir.display()
            )));
        }

        // Find the source file for this tool
        let source_file = source_dir.join(format!("{tool_name}.rs"));
        let source_content = if source_file.exists() {
            std::fs::read_to_string(&source_file)
                .map_err(|e| err(format!("Failed to read {}: {e}", source_file.display())))?
        } else {
            // Try to find it in the directory
            let mut found = String::new();
            for entry in std::fs::read_dir(source_dir).map_err(|e| err(format!("Failed to read dir: {e}")))? {
                let entry = entry.map_err(|e| err(format!("read_dir entry: {e}")))?;
                let path = entry.path();
                if path.is_file() && path.extension().is_some_and(|ext| ext == "rs") {
                    if let Ok(content) = std::fs::read_to_string(&path) {
                        found.push_str(&content);
                        found.push('\n');
                    }
                }
            }
            found
        };

        if source_content.is_empty() {
            return Err(err(format!(
                "No Rust source found for tool '{}' in {}",
                tool_name, source_dir.display()
            )));
        }

        let signatures = parse_rust_signature(&source_content);
        let detected_permission = detect_permission(&source_content, default_permission);
        let description = format!(
            "Auto-wrapped tool: {} (port from old forge, self-evolution meta-tool)",
            tool_name
        );
        let patch = generate_tool_patch(
            tool_name,
            &description,
            &signatures,
            &detected_permission,
            source_dir_str,
        );

        if dry_run {
            Ok(json!({
                "status": "dry_run",
                "tool_name": tool_name,
                "patch": patch,
            }))
        } else {
            // Write the generated code to a new file in the target directory
            let code = patch["generated_code"].as_str().unwrap_or("");
            let target_path = source_dir.join(format!("wrappers_{tool_name}.rs"));
            std::fs::write(&target_path, code)
                .map_err(|e| err(format!("Failed to write wrapper: {e}")))?;
            Ok(json!({
                "status": "generated",
                "tool_name": tool_name,
                "output_path": target_path.to_string_lossy(),
                "patch": patch,
                "review_required": true,
            }))
        }
    }
}

/// Register auto_wrap_tool into a router.
pub fn register_all(router: &ToolRouter) -> ForgeResult<()> {
    router.register(Box::new(AutoWrapTool::new()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_auto_wrap_dry_run() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("text_embed.rs");
        std::fs::write(&file, "pub async fn text_embed(text: &str) -> Vec<f32> { vec![] }\n").unwrap();

        let tool = AutoWrapTool::new();
        let result = tool
            .invoke(json!({
                "tool_name": "text_embed",
                "source_dir": dir.path().to_str().unwrap(),
                "dry_run": true
            }))
            .await
            .unwrap();

        assert_eq!(result["status"], "dry_run");
        assert_eq!(result["tool_name"], "text_embed");
        assert!(result["patch"]["generated_code"]
            .as_str()
            .unwrap()
            .contains("TextEmbedTool"));
    }

    #[tokio::test]
    async fn test_auto_wrap_write() {
        let dir = tempfile::tempdir().unwrap();
        let file = dir.path().join("csv_parse.rs");
        std::fs::write(&file, "pub fn csv_parse(text: &str) -> Vec<Vec<String>> { vec![] }\n").unwrap();

        let tool = AutoWrapTool::new();
        let result = tool
            .invoke(json!({
                "tool_name": "csv_parse",
                "source_dir": dir.path().to_str().unwrap(),
                "dry_run": false
            }))
            .await
            .unwrap();

        assert_eq!(result["status"], "generated");
        let out_path = result["output_path"].as_str().unwrap();
        assert!(Path::new(out_path).exists());
        let content = std::fs::read_to_string(out_path).unwrap();
        assert!(content.contains("CsvParseTool"));
    }

    #[tokio::test]
    async fn test_auto_wrap_missing_source() {
        let dir = tempfile::tempdir().unwrap();
        let tool = AutoWrapTool::new();
        let result = tool
            .invoke(json!({
                "tool_name": "nonexistent",
                "source_dir": dir.path().to_str().unwrap(),
                "dry_run": true
            }))
            .await;
        assert!(result.is_err());
    }

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(to_pascal_case("text_embed"), "TextEmbed");
        assert_eq!(to_pascal_case("csv_parse"), "CsvParse");
        assert_eq!(to_pascal_case("pdf_parse"), "PdfParse");
    }
}
